-- 1
SELECT LASTNAME, SALARY, DECIMAL(SALARY * 0.05, 9, 2) AS "INC-Y-SALARY", 
                         DECIMAL(SALARY * 0.05 / 12, 9, 2) AS "INC-M-SALARY"
  FROM EMPLOYEE
  WHERE SALARY <= 20000
  ORDER BY SALARY;
  
-- 2
SELECT LASTNAME, EDLEVEL, SALARY + 1200 AS "NEW-SALARY", DECIMAL(BONUS / 2, 9, 2) AS "NEW-BONUS"  
  FROM EMPLOYEE
  WHERE EDLEVEL IN (18, 20)                   
  -- WHERE EDLEVEL = 18 OR EDLEVEL = 20
  ORDER BY EDLEVEL DESC, SALARY;
  
-- 3
SELECT WORKDEPT, LASTNAME, SALARY, SALARY - 1000 AS "DECR-SALARY"
  FROM EMPLOYEE
  WHERE WORKDEPT = 'D11' AND SALARY >= 20000*80/100 AND SALARY <= 20000*120/100
  -- WHERE SALARY BETWEEN 20000*0.80 AND 20000*1.20
  ORDER BY SALARY;
  
-- 4
SELECT WORKDEPT, LASTNAME, SALARY + COMM + BONUS AS INCOME
  FROM EMPLOYEE
  WHERE WORKDEPT = 'D11' AND SALARY + COMM + BONUS > SALARY*10/100
  ORDER BY INCOME DESC;
  
-- 5 
SELECT DEPTNO, DEPTNAME, COALESCE(MGRNO, 'UNKNOWN') AS MGRNO
  FROM DEPARTMENT
  WHERE MGRNO IS NULL;

-- 6
SELECT PROJNO, COALESCE(MAJPROJ, 'MAIN PROJECT') AS "MAJOR PROJECT"
  FROM PROJECT
  WHERE PROJNO LIKE 'MA%'    
  -- WHERE SUBSTR(PROJNO,1,2) ='MA' 
  ORDER BY PROJNO;

-- 7
SELECT EMPNO, LASTNAME, YEAR(HIREDATE - BIRTHDATE) AS "AGE"
  FROM EMPLOYEE
  WHERE YEAR(HIREDATE - BIRTHDATE) < 25
  ORDER BY AGE, EMPNO;
  
-- 8
SELECT YEAR(PRSTDATE) AS YEAR, MONTH(PRSTDATE) AS MONTH, PROJNO
  FROM PROJECT
  WHERE PRENDATE = '1982-12-01'
  ORDER BY PROJNO;
  
-- 9
SELECT PROJNO, DECIMAL((DAYS(PRENDATE)-DAYS(PRSTDATE))/7.0+0.05,8,1) AS WEEKS
  FROM PROJECT
  WHERE PROJNO LIKE 'MA%'
  ORDER BY PROJNO;

-- 10
SELECT PROJNO, PRENDATE AS ESTIMATED, PRSTDATE + ((DAYS(PRENDATE) - DAYS(PRSTDATE))*1.1) DAYS AS EXPECTED 
  FROM PROJECT
  WHERE PROJNO LIKE 'MA%'
  ORDER BY PROJNO;
  
-- 11
SELECT DAYS('2000-01-01')- DAYS('1969-07-20') AS DAYS 
  FROM EMPLOYEE  
  WHERE EMPNO = '000010' 
  