SET SCHEMA FN71596;

-- 1
CREATE TABLE EMPDEPT (
  EMPNO CHAR(6) NOT NULL,
  LASTNAME VARCHAR(15) NOT NULL,
  SALARY DECIMAL(9,2) NOT NULL CHECK(SALARY <= 50000),
  DEPTNO CHAR(6) NOT NULL,
  DEP_NAME VARCHAR(36) NOT NULL,
  
  CONSTRAINT DEPT_SAL CHECK(SALARY <= 28000 OR DEPTNO <> 'E11')
);

CREATE UNIQUE INDEX EMPIND ON EMPDEPT(EMPNO);

CREATE TABLE HEIG_SALARY_RAISE (
  EMPNO CHAR(6) NOT NULL,
  PREV_SAL DECIMAL(9,2) NOT NULL,
  NEW_SAL DECIMAL(9,2) NOT NULL
);

-- 2
ALTER TABLE EMPDEPT ADD PRIMARY KEY(EMPNO);
ALTER TABLE EMPDEPT ADD FOREIGN KEY(EMPNO) REFERENCES EMPLOYEE ON DELETE CASCADE;
ALTER TABLE EMPDEPT ADD FOREIGN KEY(DEPTNO) REFERENCES DEPARTMENT ON DELETE RESTRICT;

-- 3
CREATE TRIGGER HIGH_SAL 
  AFTER UPDATE OF SALARY ON EMPDEPT 
  REFERENCING  OLD AS O    NEW AS N 
  FOR EACH ROW 
  MODE DB2SQL 
  WHEN (N.SALARY >= O.SALARY * 1.1) 
  INSERT INTO HIGH_SALARY_RAISE 
              VALUES (N.EMPNO, O.SALARY, N.SALARY) 