
-- 1
SELECT EMPNO, LASTNAME, SALARY, WORKDEPT
  FROM EMPLOYEE
  WHERE SALARY BETWEEN 22000 AND 24000 AND WORKDEPT IN ('D11', 'D21');
  
-- 2
SELECT MIN(SALARY) AS MIN, MAX(SALARY) AS MAX, DECIMAL(AVG(SALARY), 8,2) AS AVG, COUNT(*) AS COUNT
  FROM EMPLOYEE
  WHERE EDLEVEL = 16;
   
-- 3
SELECT WORKDEPT, MIN(SALARY) AS MIN, MAX(SALARY) AS MAX, DECIMAL(AVG(SALARY), 8, 2), COUNT(*) AS COUNT
  FROM EMPLOYEE
  GROUP BY WORKDEPT
  HAVING COUNT(*) > 5;
  
-- 4
SELECT WORKDEPT, SEX, SUM(SALARY) AS SUM, MIN(SALARY) AS MIN, MAX(SALARY) AS MAX
  FROM EMPLOYEE
  WHERE WORKDEPT LIKE 'D%'
  GROUP BY CUBE(WORKDEPT, SEX);

-- 5
SELECT WORKDEPT, DECIMAL(AVG(SALARY), 8, 2) AS AVG_SAL, RANK () OVER(ORDER BY AVG(SALARY)) AS RANK_SAL
  FROM EMPLOYEE
  GROUP BY WORKDEPT
  ORDER BY WORKDEPT;
  
  