-- 1
SELECT LASTNAME, FIRSTNME, 'BEFORE A RAISE' AS WHEN, SALARY
  FROM EMPLOYEE
  WHERE WORKDEPT = 'D21' AND JOB <> 'MANAGER'
  
UNION ALL

SELECT LASTNAME, FIRSTNME, 'AFTER A RAISE' AS WHEN, SALARY * 1.1
  FROM EMPLOYEE
  WHERE WORKDEPT = 'D21' AND JOB <> 'MANAGER'
  ORDER BY LASTNAME, FIRSTNME, WHEN DESC;
  
-- 2
SELECT WORKDEPT, EMPNO, SALARY
  FROM EMPLOYEE
  WHERE WORKDEPT = 'A00'
  
UNION ALL

SELECT WORKDEPT, 'ALL', SUM(SALARY)
  FROM EMPLOYEE
  WHERE WORKDEPT = 'A00'
  GROUP BY WORKDEPT
  ORDER BY 3;
  
-- 3
SELECT DEPTNO, 'DEPARTMENT' AS INFO, DEPTNAME, 1
  FROM DEPARTMENT
  WHERE DEPTNO IN ('A00', 'B01', 'C01')
  
UNION ALL

SELECT DEPTNO, PROJNO AS INFO, PROJNAME, 2
  FROM PROJECT
  WHERE DEPTNO IN ('A00', 'B01', 'C01')
  
UNION ALL

SELECT WORKDEPT, EMPNO AS INFO, LASTNAME, 3
  FROM EMPLOYEE
  WHERE WORKDEPT IN ('A00', 'B01', 'C01')
  ORDER BY DEPTNO, 4;
   
-- 4
SELECT 'PROJECT', PROJNO, RESPEMP, PRSTDATE, PRENDATE 
  FROM PROJECT
  WHERE PROJNO LIKE 'IF%'
  
UNION ALL
  
SELECT ' ', PROJNO, EMPNO, EMSTDATE, EMENDATE 
  FROM EMP_ACT
  WHERE PROJNO LIKE 'IF%'
  ORDER BY 2, 1 DESC, 3, 4;