-- 1
SELECT WORKDEPT, EMPNO, LASTNAME
  FROM VEMPLOYEE, VDEPARTMENT
  WHERE DEPTNAME = 'INFORMATION CENTER' AND WORKDEPT = DEPTNO
  ORDER BY EMPNO;
  
-- 2
SELECT WORKDEPT, EMPNO, LASTNAME
  FROM VEMPLOYEE INNER JOIN VDEPARTMENT ON WORKDEPT = DEPTNO
  WHERE DEPTNAME = 'INFORMATION CENTER'
  ORDER BY EMPNO;
  
-- 3
SELECT EMPNO, LASTNAME, DEPTNO, PROJNAME
  FROM VEMPLOYEE INNER JOIN VPROJECT ON WORKDEPT = DEPTNO
  ORDER BY EMPNO, PROJNAME;
  
-- 4
SELECT EMPNO, LASTNAME, WORKDEPT, PROJNAME
  FROM VEMPLOYEE LEFT OUTER JOIN VPROJECT ON WORKDEPT = DEPTNO
  ORDER BY EMPNO;
  
-- 5
SELECT EMPNO, LASTNAME, WORKDEPT, PROJNAME 
  FROM VEMPLOYEE RIGHT OUTER JOIN VPROJECT ON WORKDEPT = DEPTNO
  ORDER BY EMPNO, PROJNAME;
  
-- 6
SELECT EMPNO, LASTNAME, WORKDEPT, PROJNAME  
  FROM VEMPLOYEE FULL OUTER JOIN VPROJECT ON WORKDEPT = DEPTNO
  ORDER BY LASTNAME, PROJNAME;

