SET SCHEMA FN71596;

CREATE TABLE AIRLINES (
  CODE CHAR(2) NOT NULL PRIMARY KEY,
  NAME_AIRLINE VARCHAR(20) NOT NULL
);

CREATE TABLE FLIGHTS (
  AIRLINE_CODE CHAR(2) NOT NULL REFERENCES AIRLINES(CODE),
  FLIGHT_NUMBER INT NOT NULL PRIMARY KEY CONSTRAINT FL_NUMBER CHECK(FLIGHT_NUMBER > 999 AND FLIGHT_NUMBER <= 9999),
  FLIGHT_DATE DATE NOT NULL,
  PRICE REAL NOT NULL CONSTRAINT FL_PRICE CHECK(PRICE > 0),
  CURRENCY CHAR(3) NOT NULL DEFAULT 'EUR',
  MAX_ECON_CAP INT NOT NULL CONSTRAINT FL_MAX_ECON_CAP CHECK(MAX_ECON_CAP > 0),
  OCC_ECON_CAP INT NOT NULL CONSTRAINT FL_OCC_ECON_CAP CHECK(OCC_ECON_CAP >= 0),
  MAX_BUSS_CAP INT NOT NULL CONSTRAINT FL_MAX_BUSS_CAP CHECK(MAX_BUSS_CAP > 0),
  OCC_BUSS_CAP INT NOT NULL CONSTRAINT FL_OCC_BUSS_CAP CHECK(OCC_BUSS_CAP >= 0),
  PAYMENTSUM DECIMAL(16,2) NOT NULL ,
  CHECK(OCC_ECON_CAP <= MAX_ECON_CAP),
  CHECK(OCC_BUSS_CAP <= MAX_BUSS_CAP)
);  
         
CREATE TABLE SCHEDULES (
  AIRLINE_CODE CHAR(2) NOT NULL REFERENCES AIRLINES(CODE) PRIMARY KEY,
  FLIGHT_NUMBER INT NOT NULL REFERENCES FLIGHTS(FLIGHT_NUMBER) 
                          CONSTRAINT B_FL_NUM CHECK(FLIGHT_NUMBER > 999 AND FLIGHT_NUMBER <= 9999),
  DEPT_COUNTRY CHAR(2) NOT NULL,
  DEPT_CITY VARCHAR(20) NOT NULL,
  DEPT_AIRPORT CHAR(3) NOT NULL,
  DEPT_TIME TIME NOT NULL,
  ARRV_COUNTRY CHAR(2) NOT NULL,
  ARRV_CITY VARCHAR(20) NOT NULL,
  ARRV_AIRPORT CHAR(3) NOT NULL,
  ARRV_TIME TIME NOT NULL,
  FLIGHT_TIME INT NOT NULL CONSTRAINT S_FL_TIME CHECK(FLIGHT_TIME > 0),
  DISTANCE REAL NOT NULL CONSTRAINT S_DISTANCE CHECK(DISTANCE > 0)                        
);

CREATE TABLE BOOKINGS (
  AIRLINE_CODE CHAR(2) NOT NULL REFERENCES AIRLINES(CODE),
  FLIGHT_NUMBER INT NOT NULL REFERENCES FLIGHTS(FLIGHT_NUMBER) 
                          CONSTRAINT B_FL_NUM CHECK(FLIGHT_NUMBER > 999 AND FLIGHT_NUMBER <= 9999),
  BOOKING_NUMBER INT NOT NULL PRIMARY KEY CONSTRAINT B_NUMBER 
                          CHECK(BOOKING_NUMBER > 9999999 AND BOOKING_NUMBER <= 9999999),
  CUSTOMER_NUMBER INT NOT NULL CONSTRAINT B_C_NUMBER 
                          CHECK(CUSTOMER_NUMBER > 9999999 AND CUSTOMER_NUMBER <= 9999999),                                                               
  ORDER_DATE DATE NOT NULL
); 
  
ALTER TABLE SCHEDULES ADD CONSTRAINT D_TIME CHECK(DEPT_TIME < ARRV_TIME); 

CREATE UNIQUE INDEX AIRLINES_IND ON AIRLINES(NAME_AIRLINE);

CREATE TRIGGER ORD_DATE 
  BEFORE INSERT ON FN71596.BOOKINGS
  REFERENCING NEW AS N 
  FOR EACH ROW
  WHEN (N.ORDER_DATE > (SELECT FLIGHT_DATE
                          FROM FN71596.FLIGHTS
                          WHERE FLIGHT_NUMBER = N.FLIGHT_NUMBER))
  SET N.ORDER_DATE = (SELECT FLIGHT_DATE
                        FROM FN71596.FLIGHTS
                        WHERE FLIGHT_NUMBER = N.FLIGHT_NUMBER);