-- 1
SELECT E.LASTNAME, E.FIRSTNME, D.DEPTNAME
  FROM EMPLOYEE E, DEPARTMENT D
  WHERE E.WORKDEPT = D.DEPTNO
  ORDER BY D.DEPTNAME, E.LASTNAME, E.FIRSTNME;

SELECT E.LASTNAME, E.FIRSTNME, D.DEPTNAME
  FROM EMPLOYEE E JOIN DEPARTMENT D ON E.WORKDEPT = D.DEPTNO
  ORDER BY D.DEPTNAME, E.LASTNAME, E.FIRSTNME;
  
-- 2
SELECT E.LASTNAME, E.FIRSTNME, D.DEPTNAME, E.JOB
  FROM EMPLOYEE E, DEPARTMENT D
  WHERE E.WORKDEPT = D.DEPTNO AND E.WORKDEPT BETWEEN 'A02' AND 'D22' AND JOB <> 'MANAGER'
  ORDER BY D.DEPTNAME, E.LASTNAME, E.FIRSTNME;
  
SELECT E.LASTNAME, E.FIRSTNME, D.DEPTNAME, E.JOB
  FROM EMPLOYEE E JOIN DEPARTMENT D ON E.WORKDEPT = D.DEPTNO
  WHERE E.WORKDEPT BETWEEN 'A02' AND 'D22' AND JOB <> 'MANAGER'
  ORDER BY D.DEPTNAME, E.LASTNAME, E.FIRSTNME;
  
-- 3
SELECT D.DEPTNAME, E.LASTNAME, E.FIRSTNME
  FROM DEPARTMENT D, EMPLOYEE E
  WHERE D.MGRNO = E.EMPNO
  ORDER BY D.DEPTNAME;
  
SELECT D.DEPTNAME, E.LASTNAME, E.FIRSTNME
  FROM DEPARTMENT D JOIN EMPLOYEE E ON D.MGRNO = E.EMPNO
  ORDER BY D.DEPTNAME;
  
-- 4
SELECT D.DEPTNAME, E.LASTNAME, E.FIRSTNME
  FROM DEPARTMENT D, EMPLOYEE E
  WHERE D.DEPTNO = E.WORKDEPT AND JOB = 'MANAGER'
  ORDER BY D.DEPTNAME;
  
SELECT D.DEPTNAME, E.LASTNAME, E.FIRSTNME
  FROM DEPARTMENT D JOIN EMPLOYEE E ON D.DEPTNO = E.WORKDEPT
  WHERE JOB = 'MANAGER'
  ORDER BY D.DEPTNAME;
  
-- 5
SELECT DISTINCT P.PROJNO, P.PROJNAME, EM.ACTNO
  FROM PROJECT P, EMP_ACT EM
  WHERE P.PROJNO LIKE 'AD%' AND P.PROJNO = EM.PROJNO
  ORDER BY P.PROJNO, EM.ACTNO;
  
SELECT DISTINCT P.PROJNO, P.PROJNAME, EM.ACTNO
  FROM PROJECT P JOIN EMP_ACT EM ON P.PROJNO = EM.PROJNO
  WHERE P.PROJNO LIKE 'AD%'
  ORDER BY P.PROJNO, EM.ACTNO;
  
-- 6
SELECT DISTINCT E.EMPNO, E.LASTNAME, EM.PROJNO
  FROM EMPLOYEE E, EMP_ACT EM
  WHERE EM.PROJNO = 'AD3113' AND E.EMPNO = EM.EMPNO
  ORDER BY E.EMPNO, EM.PROJNO;
  
SELECT DISTINCT E.EMPNO, E.LASTNAME, EM.PROJNO
  FROM EMPLOYEE E JOIN EMP_ACT EM ON E.EMPNO = EM.EMPNO
  WHERE EM.PROJNO = 'AD3113'
  ORDER BY E.EMPNO, EM.PROJNO;
  
-- 7
SELECT EMPNO, P.PROJNO, P.PROJNAME, EM.ACTNO, EM.EMSTDATE
  FROM EMP_ACT EM, PROJECT P
  WHERE EMSTDATE = '1982-10-01' AND EM.PROJNO = P.PROJNO
  ORDER BY P.PROJNO, EMPNO, EM.ACTNO;
  
SELECT EMPNO, P.PROJNO, P.PROJNAME, EM.ACTNO, EM.EMSTDATE
  FROM EMP_ACT EM JOIN PROJECT P ON EM.PROJNO = P.PROJNO
  WHERE EMSTDATE = '1982-10-01'
  ORDER BY P.PROJNO, EMPNO, EM.ACTNO;
  
-- 8
SELECT E.WORKDEPT, E.LASTNAME, P.PROJNAME, EM.ACTNO 
  FROM EMPLOYEE E, EMP_ACT EM, PROJECT P
  WHERE E.EMPNO = EM.EMPNO AND P.PROJNO = EM.PROJNO AND E.WORKDEPT = 'A00'
  ORDER BY P.PROJNAME, EM.ACTNO;

SELECT E.WORKDEPT, E.LASTNAME, P.PROJNAME, EM.ACTNO 
  FROM EMPLOYEE E JOIN EMP_ACT EM ON E.EMPNO = EM.EMPNO JOIN PROJECT P ON P.PROJNO = EM.PROJNO
  WHERE E.WORKDEPT = 'A00'
  ORDER BY P.PROJNAME, EM.ACTNO;
  
-- 9
SELECT DISTINCT E.WORKDEPT, E.LASTNAME, P.PROJNAME, EM.ACTNO 
  FROM EMPLOYEE E, PROJECT P, EMP_ACT EM
  WHERE E.WORKDEPT BETWEEN 'A00' AND 'C01' AND EM.PROJNO = P.PROJNO AND E.EMPNO = EM.EMPNO
  ORDER BY E.WORKDEPT, E.LASTNAME, EM.ACTNO;
  
SELECT DISTINCT E.WORKDEPT, E.LASTNAME, P.PROJNAME, EM.ACTNO 
  FROM EMPLOYEE E JOIN EMP_ACT EM ON E.EMPNO = EM.EMPNO JOIN PROJECT P ON EM.PROJNO = P.PROJNO
  WHERE E.WORKDEPT BETWEEN 'A00' AND 'C01'
  ORDER BY E.WORKDEPT, E.LASTNAME, EM.ACTNO;
  
-- 10
SELECT EM.ACTNO, D.MGRNO, EM. EMSTDATE, P.PROJNO, E.LASTNAME
  FROM EMPLOYEE E, PROJECT P, DEPARTMENT D, EMP_ACT EM
  WHERE EM.EMSTDATE >= '1982-10-15' AND E.EMPNO = EM.EMPNO AND E.WORKDEPT = D.DEPTNO 
    AND EM.PROJNO = P.PROJNO
  ORDER BY EM.ACTNO, EM. EMSTDATE;
  
SELECT EM.ACTNO, D.MGRNO, EM. EMSTDATE, P.PROJNO, E.LASTNAME
  FROM EMPLOYEE E JOIN EMP_ACT EM ON E.EMPNO = EM.EMPNO JOIN PROJECT P ON EM.PROJNO = P.PROJNO
    JOIN DEPARTMENT D ON E.WORKDEPT = D.DEPTNO
  WHERE EM.EMSTDATE >= '1982-10-15'
  ORDER BY EM.ACTNO, EM. EMSTDATE;
  
-- 11
SELECT D.DEPTNO, M.LASTNAME AS MANAGER, E.LASTNAME AS EMPLOYEE, M.HIREDATE AS M_HIREDATE, 
   E.HIREDATE AS E_HIREDATE 
 FROM EMPLOYEE M, EMPLOYEE E, DEPARTMENT D
 WHERE E.WORKDEPT = 'A00' AND D.MGRNO = M.EMPNO AND E.WORKDEPT = D.DEPTNO AND M.HIREDATE > E.HIREDATE
 ORDER BY EMPLOYEE;
  
SELECT D.DEPTNO, M.LASTNAME AS MANAGER, E.LASTNAME AS EMPLOYEE, M.HIREDATE AS M_HIREDATE, 
   E.HIREDATE AS E_HIREDATE
  FROM EMPLOYEE M JOIN DEPARTMENT D ON D.MGRNO = M.EMPNO JOIN EMPLOYEE E ON E.WORKDEPT = D.DEPTNO
  WHERE E.WORKDEPT = 'A00' AND M.HIREDATE > E.HIREDATE
  ORDER BY EMPLOYEE;
