-- 1
SELECT EMPNO, LASTNAME, BIRTHDATE, SALARY
  FROM EMPLOYEE
  WHERE SALARY > 30000
  ORDER BY SALARY DESC;

-- 2
SELECT LASTNAME, FIRSTNME, WORKDEPT
  FROM EMPLOYEE
  ORDER BY WORKDEPT DESC, LASTNAME DESC;

-- 3
SELECT DISTINCT EDLEVEL
  FROM EMPLOYEE
  ORDER BY EDLEVEL DESC;

-- 4
SELECT DISTINCT EMPNO, PROJNO
  FROM EMP_ACT
  WHERE EMPNO <= '000100'
  ORDER BY EMPNO;

-- 5
SELECT LASTNAME, SALARY, BONUS
  FROM EMPLOYEE
  WHERE SEX = 'M';

-- 6
SELECT LASTNAME, SALARY, COMM
  FROM EMPLOYEE
  WHERE SALARY > 20000 AND HIREDATE >= '1980-01-01';
  
-- 7 
SELECT LASTNAME, SALARY, BONUS, COMM
  FROM EMPLOYEE
  WHERE (SALARY > 22000 AND BONUS = 400) OR (BONUS = 500 AND COMM < 1900)
  ORDER BY LASTNAME;
  
-- 8
SELECT LASTNAME, SALARY, BONUS, COMM
  FROM EMPLOYEE
  WHERE SALARY > 22000 AND BONUS IN (400, 500) AND COMM < 1900
  ORDER BY LASTNAME;
  
-- 9
SELECT PROJNO, ACTNO, EMSTDATE, EMENDATE
  FROM EMP_ACT
  WHERE PROJNO LIKE 'AD%' AND ACTNO IN (10, 80, 180)
  ORDER BY PROJNO, ACTNO;
  
-- 10
SELECT MRGNO, DEPTNO
  FROM DEPARTMENT
  WHERE MRGNO IS NOT NULL
  ORDER BY MRGNO;
  
-- 11
SELECT EMPNO, LASTNAME, SALARY, BONUS
  FROM EMPLOYEE
  WHERE BONUS BETWEEN 800 AND 1000
  ORDER BY EMPNO, BONUS;
  
-- 12
SELECT EMPNO, LASTNAME, SALARY, WORKDEPT
  FROM EMPLOYEE
  WHERE WORKDEPT BETWEEN 'A00' AND 'C01'
  ORDER BY LASTNAME, EMPNO;
  
-- 13
SELECT PROJNO, PROJNAME
  FROM PROJECT
  WHERE PROJNAME LIKE '%SUPPORT%'
  ORDER BY PROJNO;
  
-- 14
SELECT DEPTNAME, DEPTNO
  FROM DEPARTMENT
  WHERE DEPTNO LIKE '_1_'
  ORDER BY DEPTNO;
  
-- 15
SELECT LASTNAME, FIRSTNME, MIDINIT, SALARY
  FROM EMPLOYEE
  WHERE JOB NOT IN ('PRES', 'MANAGER')
  ORDER BY SALARY DESC
  FETCH FIRST 5 ROWS ONLY;
  